---

- name: Install openssl
  become: true
  ansible.builtin.shell:
    cmd: /opt/apollo/installers/install_openssl.sh
    executable: /bin/bash
  args: []
  environment:
    INSTALL_ATOM: "openssl-1.1.1w"
    INSTALL_PREFIX: "/opt/apollo/pkgs/openssl"
